# Generated by Django 5.0.4 on 2024-04-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('taille', models.PositiveIntegerField()),
                ('date_upload', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
